services:
  - type: web
    name: cloudcost-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    build:
    environment:
    PYTHON_VERSION: 3.11.9
envVars:
  - key: MONGO_URI
    value: mongodb+srv://cbtanisha10:JPbvppiNTw9APRk3@cloudcost.mjrwyxi.mongodb.net/?retryWrites=true&w=majority&appName=cloudcost
  - key: PYTHON_VERSION
    value: 3.10
