version: '3.8'

services:
  backend:
    build: ./cloudcost-backend
    ports:
      - "3001:3000"
    volumes:
      - ./cloudcost-backend:/app

  frontend:
    build: ./cloudcost-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./cloudcost-frontend:/app
