version: '3.8'

services:
  backend:
    build: ./cloudcost-backend
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./cloudcost-backend:/app

  frontend:
    build: ./cloudcost-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./cloudcost-frontend:/app
