name: Docker CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # Docker Hub login
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build & push backend image
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./cloudcost-backend
        file: ./cloudcost-backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudcost-backend:latest

    # Build & push frontend image
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./cloudcost-frontend
        file: ./cloudcost-frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudcost-frontend:latest
