name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & push backend image
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./cloudcost-backend
          file: ./cloudcost-backend/Dockerfile
          push: true
          tags: tanishaaraoo07/cloudcost-backend:latest

      # 4. Build & push frontend image
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./cloudcost-frontend
          file: ./cloudcost-frontend/Dockerfile
          push: true
          tags: tanishaaraoo07/cloudcost-frontend:latest
