name: Docker Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Docker Image
        run: docker build -t backend ./cloudcost-backend

      - name: Build Frontend Docker Image
        run: docker build -t frontend ./cloudcost-frontend
